# Step 1: Build Stage
FROM golang:1.22 AS builder
WORKDIR /app
RUN apt-get update && apt-get install -y protobuf-compiler apt-utils && rm -rf /var/lib/apt/lists/*
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go mod tidy
# Build a static binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o chunkserver .

# Step 2: Runtime Stage
FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/chunkserver .
RUN chmod +x /app/chunkserver
EXPOSE 50054
CMD ["/app/chunkserver"]
